/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppGapAnalysisRouteImport } from './routes/_app.gap-analysis'
import { Route as AppIdpRouteImport } from './routes/_app.idp'
import { Route as AppNineBoxRouteImport } from './routes/_app.nine-box'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app.employees.index'
import { Route as AppEmployeesIdRouteImport } from './routes/_app.employees.$id'
import { Route as AppSuccessProfilesIndexRouteImport } from './routes/_app.success-profiles.index'
import { Route as AppSuccessProfilesIdRouteImport } from './routes/_app.success-profiles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGapAnalysisRoute = AppGapAnalysisRouteImport.update({
  id: '/gap-analysis',
  path: '/gap-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppIdpRoute = AppIdpRouteImport.update({
  id: '/idp',
  path: '/idp',
  getParentRoute: () => AppRoute,
} as any)
const AppNineBoxRoute = AppNineBoxRouteImport.update({
  id: '/nine-box',
  path: '/nine-box',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSuccessProfilesIndexRoute = AppSuccessProfilesIndexRouteImport.update({
  id: '/success-profiles/',
  path: '/success-profiles/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuccessProfilesIdRoute = AppSuccessProfilesIdRouteImport.update({
  id: '/success-profiles/$id',
  path: '/success-profiles/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/gap-analysis': typeof AppGapAnalysisRoute
  '/idp': typeof AppIdpRoute
  '/nine-box': typeof AppNineBoxRoute
  '/progress': typeof AppProgressRoute
  '/reports': typeof AppReportsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/success-profiles/$id': typeof AppSuccessProfilesIdRoute
  '/employees/': typeof AppEmployeesIndexRoute
  '/success-profiles/': typeof AppSuccessProfilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AppDashboardRoute
  '/gap-analysis': typeof AppGapAnalysisRoute
  '/idp': typeof AppIdpRoute
  '/nine-box': typeof AppNineBoxRoute
  '/progress': typeof AppProgressRoute
  '/reports': typeof AppReportsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/success-profiles/$id': typeof AppSuccessProfilesIdRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/success-profiles': typeof AppSuccessProfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gap-analysis': typeof AppGapAnalysisRoute
  '/_app/idp': typeof AppIdpRoute
  '/_app/nine-box': typeof AppNineBoxRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/success-profiles/$id': typeof AppSuccessProfilesIdRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/success-profiles/': typeof AppSuccessProfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/dashboard'
    | '/gap-analysis'
    | '/idp'
    | '/nine-box'
    | '/progress'
    | '/reports'
    | '/employees/$id'
    | '/success-profiles/$id'
    | '/employees/'
    | '/success-profiles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/dashboard'
    | '/gap-analysis'
    | '/idp'
    | '/nine-box'
    | '/progress'
    | '/reports'
    | '/employees/$id'
    | '/success-profiles/$id'
    | '/employees'
    | '/success-profiles'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/dashboard'
    | '/_app/gap-analysis'
    | '/_app/idp'
    | '/_app/nine-box'
    | '/_app/progress'
    | '/_app/reports'
    | '/_app/employees/$id'
    | '/_app/success-profiles/$id'
    | '/_app/employees/'
    | '/_app/success-profiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gap-analysis': {
      id: '/_app/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/gap-analysis'
      preLoaderRoute: typeof AppGapAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/idp': {
      id: '/_app/idp'
      path: '/idp'
      fullPath: '/idp'
      preLoaderRoute: typeof AppIdpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nine-box': {
      id: '/_app/nine-box'
      path: '/nine-box'
      fullPath: '/nine-box'
      preLoaderRoute: typeof AppNineBoxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/success-profiles/': {
      id: '/_app/success-profiles/'
      path: '/success-profiles'
      fullPath: '/success-profiles/'
      preLoaderRoute: typeof AppSuccessProfilesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/success-profiles/$id': {
      id: '/_app/success-profiles/$id'
      path: '/success-profiles/$id'
      fullPath: '/success-profiles/$id'
      preLoaderRoute: typeof AppSuccessProfilesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGapAnalysisRoute: typeof AppGapAnalysisRoute
  AppIdpRoute: typeof AppIdpRoute
  AppNineBoxRoute: typeof AppNineBoxRoute
  AppProgressRoute: typeof AppProgressRoute
  AppReportsRoute: typeof AppReportsRoute
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppSuccessProfilesIdRoute: typeof AppSuccessProfilesIdRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppSuccessProfilesIndexRoute: typeof AppSuccessProfilesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGapAnalysisRoute: AppGapAnalysisRoute,
  AppIdpRoute: AppIdpRoute,
  AppNineBoxRoute: AppNineBoxRoute,
  AppProgressRoute: AppProgressRoute,
  AppReportsRoute: AppReportsRoute,
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppSuccessProfilesIdRoute: AppSuccessProfilesIdRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppSuccessProfilesIndexRoute: AppSuccessProfilesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
